Add intel-oneapi-compiler into pcluster image
spack/gitlab-runners pull request #52
Opened 2024-05-08 11:09 UTC by stephenmsachs

- This image is intended only to be used within the spack gitlab runners.
- Remove as much as possible after installation to minimize image size.

2024-05-08 11:11 UTC, stephenmsachs commented
This supersedes  @rscohn2's https://github.com/spack/gitlab-runners/pull/51.

2024-05-13 14:48 UTC, rscohn2 approved these changes
Looks good. Thanks!

2024-05-13 15:55 UTC, stephenmsachs commented
@alalazo can you please review? I ran https://gitlab.spack.io/spack/spack/-/pipelines/703987 with this container. It seems to work as expected.

One thing I am not sure of is the `spack clean -a`. I want to minimize the image size, but at the same time not waste time in the buildcache stack. I see there is some time spent in `source spack/share/spack/setup-env.sh` in the stack containers. Are there temporary files deleted during `spack clean -a` which get re-created during `source spack/share/spack/setup-env.sh`? If this is the case, we could use a finer granularity `spack clean`.

2024-05-27 14:13 UTC, alalazo requested changes
I inspected the last layer, not sure the modifications are what we expect. Can you comment / confirm:

![Screenshot from 2024-05-27 16-12-30](https://github.com/spack/gitlab-runners/assets/4199709/a3c4509b-2cde-435a-8083-6bcf721ca897)

I checked the layer using https://github.com/wagoodman/dive

2024-05-27 14:26 UTC, stephenmsachs commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +    && rm -rf $(find $(spack find --format '{prefix}' intel-oneapi-compilers) -type d -name 'conda_channel') \
The classic compilers are just a wrapper around the actual `intel-oneapi-compilers`. I clean up in the actual compilers directories to free up some space where possible.

2024-05-27 14:38 UTC, stephenmsachs commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +ARG SPACK_TAG="develop-2023-08-06"
When a gitlab stack is running using this container, the concretizer will identify some of the dependencies, e.g. `cmake@3.27.9%intel@2021.10.0` as pre-existing in the binary cache. This `cmake` includes some `RPATH` entries to C++ libraries inside the Intel compiler's directory. So, the `intel-oneapi-compilers` package needs to have the same location (e.g. the same hash) as it had when we first started populating the cache with Intel compiled packages.
We can update to a newer `SPACK_TAG` as soon as we use a newer Intel compiler version. Unfortunately this is currently the last one with full classic [C compiler support](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/intel-oneapi-compilers-classic/package.py#L61).

2024-05-27 14:39 UTC, stephenmsachs commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +    && curl -sL https://github.com/spack/spack/pull/40561.patch | patch -p1 \
The same reason as above. These patches are necessary to make the Fortran compiler work, but had not been merged in the last available github tag when we added the intel based stacks.

2024-05-27 14:41 UTC, stephenmsachs commented
> I inspected the last layer, not sure the modifications are what we expect. Can you comment / confirm:
> 
> ![Screenshot from 2024-05-27 16-12-30](https://private-user-images.githubusercontent.com/4199709/334131769-a3c4509b-2cde-435a-8083-6bcf721ca897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjAwNDMsIm5iZiI6MTcxNjgxOTc0MywicGF0aCI6Ii80MTk5NzA5LzMzNDEzMTc2OS1hM2M0NTA5Yi0yY2RlLTQzNWEtODA4My02YmNmNzIxY2E4OTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMTQyMjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhhN2VjNGUxOTNiYzRjODQzNmMwY2M4NTMwYjVmYjBjYmVkMjAyMzY4YzExOTAxNjVlODg2MjVmYzE1YTM0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BnnzLIPVsjtoBZR0vQHzG1EnVWuLD5CeXKybOJNeEhg)
> 
> I checked the layer using https://github.com/wagoodman/dive

Looks good to me, except for the `/etc/OpenCL`. I don't believe we need this. @rscohn2 do you know if we can delete those files?

2024-05-27 15:28 UTC, alalazo commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +    && rm -rf $(find $(spack find --format '{prefix}' intel-oneapi-compilers) -type d -name 'conda_channel') \
I'm confused, which compilers would you need? The classic compilers have been deprecated, and currently only `ifort` is shipped with the last `oneapi` releases.

2024-05-27 15:31 UTC, alalazo commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +ARG SPACK_TAG="develop-2023-08-06"
Did you check the work done on `oneapi` and `intel-oneapi-runtime`? If that's the only reason, we'd better use `%oneapi` and rely on the runtime we extract.

2024-05-27 15:35 UTC, alalazo commented
What do we use the old `spack` instance for? The one under `bootstrap-compilers/spack`. 

Also, @rscohn2 the `intel-oneapi` installation will be pushed into a public image on ghcr.io (see layer above), is that fine?

2024-05-27 22:50 UTC, rscohn2 commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +    && rm -rf $(find $(spack find --format '{prefix}' intel-oneapi-compilers) -type d -name 'conda_channel') \
The preferred version for intel-oneapi-compilers-classic is the latest release that has both icc and ifort.  I guess the issue is that this package has 2023 oneapi compilers, and 2024 and later compilers will not be tested. But that is something that could be improved over time.

2024-05-27 22:52 UTC, rscohn2 commented
> Looks good to me, except for the `/etc/OpenCL`. I don't believe we need this. @rscohn2 do you know if we can delete those files?

opencl is needed to support SYCL on CPU. The files are just the path of the shared objects so there is no space savings from deleting it.

2024-05-27 23:05 UTC, rscohn2 commented
> Also, @rscohn2 the `intel-oneapi` installation will be pushed into a public image on ghcr.io (see layer above), is that fine?

Its purpose is to support CI so it doesn't seem like redistribution to me. I cannot speak definitively for Intel. I believe this activity is moving under HPSF and we can look at all the related questions together. If the public image turns out not to be ok, I am sure we can find some other solution.

2024-05-28 07:57 UTC, stephenmsachs commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +    && rm -rf $(find $(spack find --format '{prefix}' intel-oneapi-compilers) -type d -name 'conda_channel') \
I think you are right, we can remove the the classic part altogether and pin the `intel-oneapi-compiler` version. Let me try that.

2024-05-28 08:21 UTC, stephenmsachs commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +ARG SPACK_TAG="develop-2023-08-06"
Let me look into that.

2024-09-27 07:19 UTC, stephenmsachs commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +ARG SPACK_TAG="develop-2023-08-06"
Using oneapi-runtime now.

2024-09-27 07:19 UTC, stephenmsachs commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +    && rm -rf $(find $(spack find --format '{prefix}' intel-oneapi-compilers) -type d -name 'conda_channel') \
No need to use classic compiler. Moved to using the latest oneapi compiler compatible with Amazon Linux2 `glibc`.

2024-09-30 09:33 UTC, stephenmsachs commented
I addressed the comments here and in https://github.com/spack/spack/pull/44150. It's ready to be reveiwed again.

2024-10-04 08:48 UTC, stephenmsachs commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +    && curl -sL https://github.com/spack/spack/pull/40561.patch | patch -p1 \
Patches not necessary any more since we are using a newer spack tag.

2024-10-04 10:08 UTC, alalazo approved these changes

2024-10-04 10:10 UTC, merged

2024-11-20 11:04 UTC, mabraham commented on Dockerfiles/pcluster-amazonlinux-2/Dockerfile
> +    && spack compiler add --scope site \
https://spack.readthedocs.io/en/latest/build_systems/inteloneapipackage.html suggests this line should be more like
```
spack compiler add `spack location -i intel-oneapi-compilers`/compiler/latest/bin --scope site \
```