Build Ubuntu 24.04 image in CI
spack/gitlab-runners pull request #54
Opened 2024-08-06 11:51 UTC by adamjstewart

Missed one very important line of code.

2024-08-06 11:53 UTC, alalazo approved these changes

2024-08-06 12:06 UTC, alalazo requested changes

2024-08-06 20:32 UTC, adamjstewart commented
@alalazo I'm a bit stuck on this. I thought `ENV` would pass env vars to the next `RUN` command and make them available. Can you double check what I did and see what I'm missing? It's still using the system `python3` for some reason.

2024-08-08 17:06 UTC, adamjstewart commented
Docker logic is based on https://pythonspeed.com/articles/activate-virtualenv-dockerfile/

2024-08-09 03:34 UTC, alalazo approved these changes

2024-08-09 03:34 UTC, merged